name: date_util
description: A simple dart API with a complete set of date helper methods  
             not available in the DateTime API hence, production is 
             made easier when working with dates.
version: 0.1.5
homepage: https://github.com/corpsgeek/Date-Utility
author: Adetu Ridwan, Egbesola Anthony <bethetechnology@gmail.com>

environment:
  sdk: '>=2.9.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  #test: ^0.12.0
